# Describes the format for available notification services

notify:
  fields:
    message:
      required: true
      example: The garage door has been open for 10 minutes.
      selector:
        text:
    title:
      example: "Your Garage Door Friend"
      selector:
        text:
    target:
      example: platform specific
      selector:
        object:
    data:
      example: platform specific
      selector:
        object:

send_message:
  target:
    entity:
      domain: notify
  fields:
    message:
      selector:
        text:
      filter:
        supported_features:
          - notify.NotifyEntityFeature.MESSAGE
    title:
      selector:
        text:
      filter:
        supported_features:
          - notify.NotifyEntityFeature.TITLE
    recipients:
      selector:
        select:
          options: []
          custom_value: true
          multiple: true
      filter:
        supported_features:
          - notify.NotifyEntityFeature.RECIPIENTS
    data:
      selector:
        object:
      filter:
        supported_features:
          - notify.NotifyEntityFeature.DATA

persistent_notification:
  fields:
    message:
      required: true
      example: The garage door has been open for 10 minutes.
      selector:
        text:
    title:
      example: "Your Garage Door Friend"
      selector:
        text:
    data:
      example: platform specific
      selector:
        object:
